
name: Generate Snake GIF
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Run every hour

jobs:
  update-readme:
    name: Update Readme with Snake GIF
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install GitHub Readme Stats
        run: npm install -g github-readme-stats
      - name: Generate Snake GIF
        run: github-readme-stats --snake --username your-username
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update Snake GIF"
          git push

